services:
  gitlab-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gitlab-mcp
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:8081:3000"  # Only allow local access, improve security
    user: "node"  # Use non-root user for security
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 60s
      timeout: 10s
      retries: 3