services:
  gitlab-mcp:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: gitlab-mcp
    restart: always
    env_file:
      - ../.env
    ports:
      - "127.0.0.1:8081:3000"  # Replace with your internal IP